using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.XR.Interaction.Toolkit;
using UnityEngine.InputSystem;

public class ActivateTeleportationRay : MonoBehaviour
{

    [SerializeField]
    GameObject leftTeleportation;
    [SerializeField]
    GameObject rightTeleportation;

    [SerializeField]
    InputActionProperty leftActivate;
    [SerializeField]
    InputActionProperty rightActivate;

    [SerializeField]
    InputActionProperty leftCancel;
    [SerializeField]
    InputActionProperty rightCancel;

    [SerializeField]
    XRRayInteractor rightRay;
    [SerializeField]
    XRRayInteractor leftRay;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        bool isLeftRayHovering = leftRay.TryGetHitInfo(out Vector3 leftPos, out Vector3 leftNormal, out int leftNumber, out bool leftValid);
        bool isRightRayHovering = rightRay.TryGetHitInfo(out Vector3 rightPos, out Vector3 rightNormal, out int rightNumber, out bool rightValid);
        
        leftTeleportation.SetActive(!isLeftRayHovering && leftCancel.action.ReadValue<float>() == 0 && leftActivate.action.ReadValue<float>() > 0.1f);
        rightTeleportation.SetActive(!isRightRayHovering && rightCancel.action.ReadValue<float>() == 0 && rightActivate.action.ReadValue<float>() > 0.1f);
    }
}
